# TEST

In [2]:
import numpy as np

from context import src
from src import aerodynamics as aero

In [4]:
horse_shoes = np.array([[[0.5, -4, 0], [0.5, -2, 0]],
                        [[0.5, -2, 0], [0.5, 0, 0]],
                        [[0.5, 0, 0],  [0.5, 2, 0]],
                        [[0.5, 2, 0],  [0.5, 4, 0]],
                        [[8.5, -2, 0], [8.5, 0, 0]],
                        [[8.5, 0, 0], [8.5, 2, 0]]])
                       
col_points = np.array([[1.5, -3, 0], [1.5, -1, 0], [1.5, 1, 0], [1.5, 3, 0], [9.5, -1, 0], [9.5, 1, 0]])

In [15]:
inf_coef = np.zeros((6, 6))

In [16]:
for i, col_point in enumerate(col_points):
    
    print(f"i = {i + 1}")
    
    for j, hs in enumerate(horse_shoes):
        
        point_a = hs[0]
        point_b = hs[1]
        target_point = col_point
        circulation = 1
    
        ind_velocity = aero.functions.horse_shoe_ind_vel(point_a, point_b, target_point, circulation, vortex_radius=0.001)
        inf_coef[i][j] = ind_velocity[2]
        print(f"{j + 1} : {ind_velocity[2]}")
        
    
    print("==============================================")

i = 1
1 : -0.3842340221311718
2 : 0.08170916704279163
3 : 0.01333893366257239
4 : 0.005315314768202034
5 : 0.001525498880046292
6 : 0.001309701390315123
i = 2
1 : 0.08170916704279163
2 : -0.3842340221311718
3 : 0.08170916704279163
4 : 0.01333893366257239
5 : 0.0016158276504450338
6 : 0.001525498880046292
i = 3
1 : 0.01333893366257239
2 : 0.08170916704279163
3 : -0.3842340221311718
4 : 0.08170916704279163
5 : 0.0015254988800462918
6 : 0.0016158276504450338
i = 4
1 : 0.005315314768202034
2 : 0.01333893366257239
3 : 0.08170916704279163
4 : -0.3842340221311718
5 : 0.0013097013903151228
6 : 0.0015254988800462918
i = 5
1 : 0.10515815799121793
2 : -0.3192893104624976
3 : 0.10515815799121793
4 : 0.020364331495463725
5 : -0.3842340221311718
6 : 0.08170916704279163
i = 6
1 : 0.020364331495463725
2 : 0.10515815799121793
3 : -0.3192893104624976
4 : 0.10515815799121793
5 : 0.08170916704279163
6 : -0.3842340221311718


In [17]:
print(inf_coef)

[[-0.38423402  0.08170917  0.01333893  0.00531531  0.0015255   0.0013097 ]
 [ 0.08170917 -0.38423402  0.08170917  0.01333893  0.00161583  0.0015255 ]
 [ 0.01333893  0.08170917 -0.38423402  0.08170917  0.0015255   0.00161583]
 [ 0.00531531  0.01333893  0.08170917 -0.38423402  0.0013097   0.0015255 ]
 [ 0.10515816 -0.31928931  0.10515816  0.02036433 -0.38423402  0.08170917]
 [ 0.02036433  0.10515816 -0.31928931  0.10515816  0.08170917 -0.38423402]]


In [26]:
airspeed = 100
alpha = 5 * np.pi / 180

flow_velocity = np.array([airspeed * np.cos(alpha), 0, airspeed * np.sin(alpha)])
z_component = np.dot(flow_velocity, np.array([0, 0, 1]))

rhs_vector = np.repeat(z_component, 6)
print(rhs_vector)

[8.71557427 8.71557427 8.71557427 8.71557427 8.71557427 8.71557427]


In [29]:
gamma = np.linalg.solve(inf_coef, -rhs_vector)
print(gamma)

[32.97430108 39.32161733 39.32161733 32.97430108 14.65865473 14.65865473]
