# Master Branch Performance Tests - Geometry

In [ ]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

from numpy import sin, cos, tan, pi, dot, cross
from numpy.linalg import norm

from context import flyingcircus
from flyingcircus import geometry

## rotate_point

In [25]:
np.random.seed(13)
point_coord = np.random.rand((3))
rot_axis = np.random.rand((3))
rot_center = np.random.rand((3))
rot_angle = 57
point_coord, rot_axis, rot_center, rot_angle

(array([0.77770241, 0.23754122, 0.82427853]),
 array([0.9657492 , 0.97260111, 0.45344925]),
 array([0.60904246, 0.77552651, 0.64161334]),
 57)

In [26]:
%%timeit
result = geometry.rotate_point(point_coord, rot_axis, rot_center, rot_angle)

113 µs ± 693 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## velocity_vector

In [28]:
true_airspeed = 125
alpha = 17
beta = 7
gamma = 12

In [29]:
%%timeit
velocity_vector = geometry.velocity_vector(true_airspeed, alpha, beta, gamma)

367 µs ± 2.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
