# Master Branch Performance Tests - basic_elements

In [4]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

from numpy import sin, cos, tan, pi, dot, cross
from numpy.linalg import norm

from context import src
from src import basic_elements

## vortex_segment

In [2]:
np.random.seed(13)
first_point = np.random.rand((3))
second_point = np.random.rand((3))
target_point = np.random.rand((3))
circulation = 13
first_point, second_point, target_point, circulation

(array([0.77770241, 0.23754122, 0.82427853]),
 array([0.9657492 , 0.97260111, 0.45344925]),
 array([0.60904246, 0.77552651, 0.64161334]),
 13)

In [ ]:
%%timeit
induced_velocity = basic_elements.vortex_segment(first_point, second_point, target_point, circulation)

## vortex_ring

In [7]:
vertex_coordinates = np.array([[2, 0, 0],
                               [0, 0, 0],
                               [0, 2, 0],
                               [2, 2, 0]]).transpose()

target_point = [1, 1, 0]
circulation = 1

In [8]:
%%timeit
induced_velocity = basic_elements.vortex_ring(vertex_coordinates, target_point, circulation)

1.3 ms ± 33.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## vortex_horseshoe

In [12]:
vertex_coordinates = np.array([[2, 0, 0],
                               [0, 0, 0],
                               [0, 2, 0],
                               [2, 2, 0]]).transpose()

target_point = [1, 1, 0]
circulation = 1

In [11]:
%%timeit
induced_velocity, wake_induced_velocity = basic_elements.vortex_horseshoe(vertex_coordinates,
                                                                              target_point,
                                                                              circulation)

946 µs ± 8.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
