# Performance Branch Performance Tests - Geometry

In [43]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

import math
from numba import jit, double

#from numpy import sin, cos, tan, pi, dot, cross
#from numpy.linalg import norm

In [44]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [45]:
from context import src
from src import geometry
from src import fast_operations as f

## dot

In [46]:
np.random.seed(13)
a = np.random.rand((3))
b = np.random.rand((3))
c = np.random.rand((3))
a, b, c

(array([0.77770241, 0.23754122, 0.82427853]),
 array([0.9657492 , 0.97260111, 0.45344925]),
 array([0.60904246, 0.77552651, 0.64161334]))

In [47]:
%%timeit
result = np.dot(a, b)

1.06 µs ± 32.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [48]:
%%timeit
result = f.dot(a, b)

681 ns ± 4.25 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## cross

In [51]:
%%timeit
result = np.cross(a, b)

71.7 µs ± 5.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [50]:
%%timeit
result = f.cross(a, b)

1.26 µs ± 59.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## norm

In [49]:
%%timeit
result = np.linalg.norm(a)

7.34 µs ± 182 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
%%timeit
result = f.norm(a)

543 ns ± 3.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## normalize

In [53]:
%%timeit
result = a / np.linalg.norm(a)

9.94 µs ± 75.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
%%timeit
result = f.normalize(a)

1.12 µs ± 56.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## rotate_point

In [55]:
point_coord = np.random.rand((3))
rot_axis = np.random.rand((3))
rot_center = np.random.rand((3))
rot_angle = 57
point_coord, rot_axis, rot_center, rot_angle

(array([0.72201823, 0.03503652, 0.29844947]),
 array([0.05851249, 0.85706094, 0.37285403]),
 array([0.67984795, 0.25627995, 0.34758122]),
 57)

In [56]:
%%timeit
result = geometry.rotate_point(point_coord, rot_axis, rot_center, rot_angle)

111 µs ± 7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## velocity_vector

In [57]:
true_airspeed = 125
alpha = 17
beta = 7
gamma = 12

In [58]:
%%timeit
velocity_vector = geometry.velocity_vector(true_airspeed, alpha, beta, gamma)

374 µs ± 5.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
