# Performance Branch Performance Tests - basic_elements

In [10]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

from numpy import sin, cos, tan, pi, dot, cross
from numpy.linalg import norm

In [9]:
%load_ext autoreload
%autoreload 2

In [13]:
from context import src
from src import basic_elements
from src import fast_operations as f

## vortex_segment

In [61]:
np.random.seed(13)
first_point = np.random.rand((3))
second_point = np.random.rand((3))
target_point = np.random.rand((3))
circulation = 13.
first_point, second_point, target_point, circulation

(array([0.77770241, 0.23754122, 0.82427853]),
 array([0.9657492 , 0.97260111, 0.45344925]),
 array([0.60904246, 0.77552651, 0.64161334]),
 13.0)

In [62]:
%%timeit
induced_velocity = basic_elements.vortex_segment(first_point, second_point, target_point, circulation)

2.16 µs ± 68.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## vortex_ring

In [4]:
vertex_coordinates = np.array([[2, 0, 0],
                               [0, 0, 0],
                               [0, 2, 0],
                               [2, 2, 0]]).transpose()

target_point = [1, 1, 0]
circulation = 1

In [5]:
%%timeit
induced_velocity = basic_elements.vortex_ring(vertex_coordinates, target_point, circulation)

376 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


## vortex_horseshoe

In [95]:
vertex_coordinates = np.array([[2, 0, 0],
                               [0, 0, 0],
                               [0, 2, 0],
                               [2, 2, 0]]).transpose()

target_point = np.array([1, 1, 0])
circulation = 1

In [97]:
%%timeit
induced_velocity, wake_induced_velocity = basic_elements.vortex_horseshoe(vertex_coordinates,
                                                                              target_point,
                                                                              circulation)

4.65 µs ± 30.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
