In [2]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d


In [3]:
x = np.linspace(0, 2, 11)
y = np.linspace(-5, 5, 11)
xx, yy = np.meshgrid(x, y)
zz = 0.1 * abs(yy)

In [4]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d', proj_type="persp")
ax.autoscale(False)
ax.plot_surface(xx, yy, zz)

<IPython.core.display.Javascript object>

In [5]:
Rx = np.linspace(0, 2, 5)
Rx

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:
Ry = np.zeros((5))
Ry

array([0., 0., 0., 0., 0.])

In [7]:
Tx = np.linspace(0.25, 1.25, 5)
Tx

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [8]:
Ty = np.repeat(5, 5)
Ty

array([5, 5, 5, 5, 5])

In [9]:
Py = np.linspace(0, 5, 6)
Py

array([0., 1., 2., 3., 4., 5.])

In [10]:
Rxx = np.repeat(Rx[np.newaxis], 6, axis=0)
Ryy = np.repeat(Ry[np.newaxis], 6, axis=0)
Txx = np.repeat(Tx[np.newaxis], 6, axis=0)
Tyy = np.repeat(Ty[np.newaxis], 6, axis=0)

Pyy = np.repeat(Py[np.newaxis], 5, axis=0)
Pyy = Pyy.transpose()
Pyy

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [11]:
Rxx.shape

(6, 5)

In [12]:
Pyy.shape

(6, 5)

In [13]:
Rxx + (Txx - Rxx) * (Pyy - Ryy) / (Tyy - Ryy)

array([[0.  , 0.5 , 1.  , 1.5 , 2.  ],
       [0.05, 0.5 , 0.95, 1.4 , 1.85],
       [0.1 , 0.5 , 0.9 , 1.3 , 1.7 ],
       [0.15, 0.5 , 0.85, 1.2 , 1.55],
       [0.2 , 0.5 , 0.8 , 1.1 , 1.4 ],
       [0.25, 0.5 , 0.75, 1.  , 1.25]])

In [14]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
np.flip(a, axis=0)

array([[3, 4],
       [1, 2]])

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = np.reshape(a, (a.size, 1))
z

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
c = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])[np.newaxis].transpose()
c + b

array([[2, 3, 4],
       [6, 7, 8]])

In [35]:
np.reshape(z, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a1 = np.array([1, 1])[np.newaxis]
a2 = np.array([2, 2])[np.newaxis]
a3 = np.array([3, 3])[np.newaxis]

np.concatenate((a1, a2, a3), axis=0)

array([[1, 1],
       [2, 2],
       [3, 3]])